<?php

namespace SpsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KabelTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KabelTypeRepository extends EntityRepository
{
}
