<?php

namespace SpsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MufaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MufaRepository extends EntityRepository
{


    public function getMufaKodFromID($id_mufa){

            $qb = $this->getEntityManager()
                ->createQuery(
                    'SELECT
					 m.kod, m.id
				    FROM SpsBundle:Mufa m
                 WHERE m.id = :id'

                )->setParameter('id', $id_mufa);

            $result =$qb->getScalarResult();

        return $result[0]['id'].'-'.$result[0]['kod'];

    }
	
   public function getMufy(){
   	
   		$qb = $this->getEntityManager()
   		->createQuery(
   				'SELECT  m.id,m.kod,m.opis
				    FROM SpsBundle:Mufa m
              '
   		);
   	
   		 return $qb->getResult();
   }




}
