<?php

namespace SpsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StandardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StandardRepository extends EntityRepository
{
}
