<?php

namespace SpsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WezelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WezelRepository extends EntityRepository
{
	public function getWezelFomRejon($id_rejon){
	
		$qb = $this->getEntityManager()
		->createQuery(
				'SELECT  w.id, w.name, w.opis,
							m.id as mid,
							m.kod as mkod,
							m.opis as mopis
				    FROM SpsBundle:Wezel w
					LEFT JOIN SpsBundle:Mufa m
				with m.id_wezel =  w.id
	 			'
		);
	
		return $qb->getResult();
	}
	public function getLastIdFromRejon($id_rejon){
		
		$qb = $this->getEntityManager()
		->createQuery(
				'SELECT  MAX(w.id)
				FROM SpsBundle:Wezel w
					LEFT JOIN SpsBundle:Rejon r
				with w.id_rejon = r.id
				WHERE r.id =:id'
		)->setParameter('id', $id_rejon);
		
		return $qb->getSingleResult();
		
	}	
	
}
