<?php

namespace SpsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WezelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WezelRepository extends EntityRepository
{
	public function getWezelFomRejon($id_rejon){
	
		$qb = $this->getEntityManager()
		->createQuery(
				'SELECT  w.id, w.name, w.opis,
							m.id as mid,
							m.kod as mkod,
							m.opis as mopis
				    FROM SpsBundle:Wezel w
					LEFT JOIN SpsBundle:Mufa m
				with m.id_wezel =  w.id
	 			WHERE m.id_rejon='.$id_rejon
		);
	
		return $qb->getResult();
	}
	
}
