<?php

namespace SpsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WloknoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WloknoRepository extends EntityRepository
{
	
	public function getWloknaEnd($id_kabel,$id_mufa){
		$qb = $this->getEntityManager()
		->createQuery(
				'SELECT w.id,IDENTITY (w.id_spaw_end) as id_spaw 
				FROM SpsBundle:Wlokno w 
				LEFT JOIN SpsBundle:Kabel k  with k.id = w.id_kabel
       	   WHERE k.id =:id_kabel  
				AND k.id_mufa_end=:id_mufa
				OR k.id_mufa_end =:id_mufa
		
				'
		)->setParameter('id_kabel', $id_kabel)
		->setParameter('id_mufa', $id_mufa)
		->getResult()
		;
		
		return $qb;
	}
	// TODO :
public function newGetWloknaStart($id_kabel,$id_mufa){
		$qb = $this->getEntityManager()
		->createQuery(
				'SELECT
				
				
					(SELECT kl.id FROM SpsBundle:Wlokno wl  
					LEFT JOIN SpsBundle:Kabel kl with wl.id_kabel=kl.id
					WHERE wl.id=w.id) as id_kabel_lewa,
				
					(SELECT m1.id FROM SpsBundle:Wlokno w1  
					LEFT JOIN SpsBundle:Kabel k1 with w1.id_kabel=k1.id
					LEFT JOIN SpsBundle:Mufa m1  with k1.id_mufa_end=m1.id
					WHERE w1.id=w.id) as id_end_lewa,
				
					(SELECT m2.kod FROM SpsBundle:Wlokno w2  
					LEFT JOIN SpsBundle:Kabel k2 with w2.id_kabel=k2.id
					LEFT JOIN SpsBundle:Mufa m2  with k2.id_mufa_end=m2.id
					WHERE w2.id=w.id) as kod_end_lewa,
				
				
					(SELECT kk2.j FROM SpsBundle:Wlokno ww2  
					LEFT JOIN SpsBundle:Kabel kk2 with ww2.id_kabel=kk2.id
					WHERE ww2.id=w.id) as j_end_lewa,
				
					(SELECT kk3.producent FROM SpsBundle:Wlokno ww3  
					LEFT JOIN SpsBundle:Kabel kk3 with ww3.id_kabel=kk3.id
					WHERE ww3.id=w.id) as producent_end_lewa,
				
					(SELECT kk4.tubs FROM SpsBundle:Wlokno ww4  
					LEFT JOIN SpsBundle:Kabel kk4 with ww4.id_kabel=kk4.id
					WHERE ww4.id=w.id) as tubs_end_lewa,
					
					(SELECT m4.id FROM SpsBundle:Wlokno w4  
					LEFT JOIN SpsBundle:Kabel k4 with w4.id_kabel=k4.id
					LEFT JOIN SpsBundle:Mufa m4  with k4.id_mufa_start=m4.id
					WHERE w4.id=w.id) as id_start_lewa,
				
					(SELECT m3.kod FROM SpsBundle:Wlokno w3  
					LEFT JOIN SpsBundle:Kabel k3 with w3.id_kabel=k3.id
					LEFT JOIN SpsBundle:Mufa m3  with k3.id_mufa_start=m3.id
					WHERE w3.id=w.id) as kod_start_lewa,
					
					w.id as id_w_lewa,
				   
					(SELECT w5.id FROM SpsBundle:Wlokno w5
					WHERE w5.id =w.id_spaw_start) as id_w_prawa,
				
					
					(SELECT m6.id FROM SpsBundle:Wlokno w6  
					LEFT JOIN SpsBundle:Kabel k6 with w6.id_kabel=k6.id
					LEFT JOIN SpsBundle:Mufa m6  with k6.id_mufa_end=m6.id
					WHERE w6.id=w.id_spaw_start) as id_start_prawa,
				
					(SELECT m7.kod FROM SpsBundle:Wlokno w7  
					LEFT JOIN SpsBundle:Kabel k7 with w7.id_kabel=k7.id
					LEFT JOIN SpsBundle:Mufa m7  with k7.id_mufa_end=m7.id
					WHERE w7.id=w.id_spaw_start) as kod_start_prawa,
				
					(SELECT kk7.producent FROM SpsBundle:Wlokno ww7  
					LEFT JOIN SpsBundle:Kabel kk7 with ww7.id_kabel=kk7.id
					WHERE ww7.id=w.id_spaw_start) as producent_start_prawa,
				
					(SELECT kk8.j FROM SpsBundle:Wlokno ww8  
					LEFT JOIN SpsBundle:Kabel kk8 with ww8.id_kabel=kk8.id
					WHERE ww8.id=w.id_spaw_start) as j_start_prawa,
				
					(SELECT kk9.tubs FROM SpsBundle:Wlokno ww9  
					LEFT JOIN SpsBundle:Kabel kk9 with ww9.id_kabel=kk9.id
					WHERE ww9.id=w.id_spaw_start) as tubs_start_prawa,
				
				
					(SELECT m8.id FROM SpsBundle:Wlokno w8  
					LEFT JOIN SpsBundle:Kabel k8 with w8.id_kabel=k8.id
					LEFT JOIN SpsBundle:Mufa m8  with k8.id_mufa_end=m8.id
					WHERE w8.id_spaw_end=w.id_spaw_start) as id_end_prawa,
					
				
					(SELECT m9.kod FROM SpsBundle:Wlokno w9  
					LEFT JOIN SpsBundle:Kabel k9 with w9.id_kabel=k9.id
					LEFT JOIN SpsBundle:Mufa m9  with k9.id_mufa_end=m9.id
					WHERE w9.id_spaw_end=w.id_spaw_start) as kod_end_prawa,
				
					(SELECT kr.id FROM SpsBundle:Wlokno wr  
					LEFT JOIN SpsBundle:Kabel kr with wr.id_kabel=kr.id
					WHERE wr.id_spaw_end=w.id_spaw_start) as id_kabel_prawa
					
				
					
				
				
					
				
				FROM SpsBundle:Wlokno w
				LEFT JOIN SpsBundle:Kabel k  with k.id = w.id_kabel
       	   WHERE k.id =:id_kabel
				AND k.id_mufa_start=:id_mufa
				
	
				'
		)->setParameter('id_kabel', $id_kabel)
		->setParameter('id_mufa', $id_mufa)
		;

		return $qb->getResult();
	}
	
	
	public function getWloknaStart($id_kabel,$id_mufa){
		$qb = $this->getEntityManager()
		->createQuery(
				'SELECT w.id,IDENTITY (w.id_spaw_start) as id_spaw
				FROM SpsBundle:Wlokno w
				LEFT JOIN SpsBundle:Kabel k  with k.id = w.id_kabel
       	   WHERE k.id =:id_kabel
				AND k.id_mufa_start=:id_mufa
				
	
				'
		)->setParameter('id_kabel', $id_kabel)
		->setParameter('id_mufa', $id_mufa)
		;
	
		return $qb->getResult();
	}
	
	
	
	
	public function  getSpawStartFromId($id){
		
			
		
		$qb = $this->getEntityManager()
		->createQuery(
				
				'SELECT k.id as id_k,w.id as id_w,m.kod,m.id as id_mufa,k.producent,
				k.j,k.tubs,k.standard,IDENTITY (k.id_mufa_end) as mufa_end
				FROM SpsBundle:Wlokno w
				LEFT JOIN SpsBundle:Kabel k  with k.id = w.id_kabel
				LEFT JOIN SpsBundle:Mufa m with k.id_mufa_start =m.id
       	   WHERE w.id =:id'
		)->setParameter('id',$id);
		
		$x=$qb->getResult();
	
		//return $x['0']['kod'];
			return  $x;
	

	}
	
	public function  getSpawEndFromId($id){
	
			
	
		$qb = $this->getEntityManager()
		->createQuery(
	
				'SELECT k.id as id_k,w.id as id_w,m.kod,m.id as id_mufa,k.producent,
				k.j,k.tubs,k.standard,IDENTITY (k.id_mufa_start) as mufa_end
				FROM SpsBundle:Wlokno w
				LEFT JOIN SpsBundle:Kabel k  with k.id = w.id_kabel
				LEFT JOIN SpsBundle:Mufa m with k.id_mufa_end =m.id
       	   WHERE w.id =:id'
		)->setParameter('id',$id);
	
		$x=$qb->getResult();
	
		//return $x['0']['kod'];
		return  $x;
	
	
	}
	
	
	public function  getFiberPosition($id){
	
			
		$qb = $this->getEntityManager()
		->createQuery('
			SELECT count(w.id), s.max
		FROM SpsBundle:Wlokno w
		LEFT JOIN SpsBundle:Kabel k  with k.id = w.id_kabel
		LEFT JOIN SpsBundle:Standard s with k.id_standard= s.id
		WHERE k.id =(SELECT IDENTITY(ww.id_kabel) FROM SpsBundle:Wlokno ww  WHERE ww.id=:id)
		AND w.id<=:id'			
	)->setParameter('id',$id);
		
		
	return  $qb->getResult();
	}
	
	public function  getFiberColor($id_count){
	
			
		$qb = $this->getEntityManager()
		->createQuery('
			SELECT s.color'.$id_count.' as color,s.nazwa'.$id_count.' as nazwa
		FROM SpsBundle:Standard s'
		
		)->getResult();
		
		
		return  $qb;
	}
	
}
