<?php

namespace SpsBundle\Entity\Repository\Types;

use Doctrine\ORM\EntityRepository;

/**
 * ObjectTypRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectTypRepository extends EntityRepository
{
	
	
	public function getAll($type){
	
		$qb = $this->getEntityManager()
		->createQuery(
				'SELECT o.name, o.id
				FROM SpsBundle:ObjectTyp o
				WHERE o.name =:name'
		)->setParameter('name', $type);
	
		return $qb->getResult();
	}
	
}
