<?php

namespace SpsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HistoriRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriRepository extends EntityRepository
{
	public function getLatestHistori($limit = null){
		
		$qb = $this->createQueryBuilder('b')
		->select('b')
		->addOrderBy('b.data');
		
		if (false === is_null($limit))
			$qb->setMaxResults($limit);
		
		return $qb->getQuery()
		->getResult();
	}
}
