<?php

namespace SpsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HistoriRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsRepository extends EntityRepository
{
	
	public function getValueFromName($name){
		$qb = $this->getEntityManager()
		->createQuery(
				'SELECT  s.value
				FROM SpsBundle:Settings s
				
       	   WHERE s.name =:name
				'
		)->setParameter('name', $name)
		->getResult();
		
		return $qb;
	}
	
	
	public function getAll(){
		$qb = $this->getEntityManager()
		->createQuery(
				'SELECT s.id, s.name, s.value
				FROM SpsBundle:Settings s		'
		)
		->getResult();
	
		return $qb;
	}
	

	public function setValueFromName($name){
		$qb = $this->getEntityManager()
		->createQuery(
				'SELECT  *
				FROM SpsBundle:Settings s
	
       	   WHERE s.name =:name
				'
		)->setParameter('id_kabel', $name)
		->getResult();
	
		
	}
	
}