<?php

namespace SpsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use SpsBundle\Entity\Standard;

/**
 * StandardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StandardRepository extends EntityRepository
{
	
	
	public function getAll(){
	
		$qb = $this->getEntityManager()
		->createQuery(
				'SELECT s.nazwa, s.id
				FROM SpsBundle:Standard s'
	
		);
	
		return $qb->getResult();
	}
	
	
}
